'use strict';
const C=CheckinCore, KEY='abstinence_checkin_state_v1', DB_NAME='AbstinenceCheckinDB', STORE='state', UNDO=KEY+'_before_import', BACKUP_TIME=KEY+'_last_export';
const $=id=>document.getElementById(id), today=()=>C.day(new Date());
let state=C.fresh(),viewDate=C.parse(today()),range='30',toastTimer,writeQueue=Promise.resolve(),dbPromise;
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function localGet(key){try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
function openDB(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('存储暂时被其他页面占用'));});return dbPromise;}
async function dbRead(key=KEY){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}
async function dbWrite(snapshot,key=KEY){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(snapshot,key);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('保存中断'));});}
function storageReport(localOK,idbOK){$('storageStatus').classList.toggle('warning',!localOK||!idbOK);$('storageStatus').textContent=localOK&&idbOK?'✓ 已保存在本机 · 两份本地存储':localOK||idbOK?'已本地保存 · 一份存储暂不可用，请导出备份':'保存失败 · 请立即导出备份，避免丢失记录';}
function persist(){state.modifiedAt=Math.max(Date.now(),state.modifiedAt+1);state.version=2;
 // Keep a v1-readable projection while retaining authoritative v2 records.
 state.checkins=Object.fromEntries(Object.entries(state.records).filter(([,r])=>r.status==='success').map(([d])=>[d,{time:new Date().toISOString()}]));
 const snapshot=JSON.parse(JSON.stringify(state));
 writeQueue=writeQueue.then(async()=>{let localOK=false,idbOK=false;try{localStorage.setItem(KEY,JSON.stringify(snapshot));localOK=true;}catch{}try{idbOK=await dbWrite(snapshot);}catch{}storageReport(localOK,idbOK);return localOK||idbOK;});return writeQueue;
}
async function load(){let local=localGet(KEY),remote=null,foundInvalid=false;try{remote=await dbRead();}catch{}const candidates=[];for(const s of [local,remote]){if(!s)continue;try{candidates.push(C.normalize(s));}catch{foundInvalid=true;}}
 candidates.sort((a,b)=>b.modifiedAt-a.modifiedAt);if(candidates.length)state=candidates[0];
 render();$('app').inert=false;
 if(foundInvalid&&!candidates.length){$('storageStatus').textContent='现有存储无法读取，请导入备份恢复；未覆盖旧数据。';$('storageStatus').classList.add('warning');}
 else{await persist();if(local?.version===1||remote?.version===1)toast('已保留旧版记录，升级完成');}
 $('undoImport').hidden=!(localGet(UNDO)||await dbRead(UNDO).catch(()=>null));
}
function rangeStart(){const t=today();if(range==='all')return state.startDate;if(range==='month')return t.slice(0,7)+'-01';return C.shift(t,-Number(range)+1);}
function render(){document.title=state.goalName;$('appTitle').textContent=state.goalName;$('mottoText').textContent=state.motto;const s=C.streaks(state);$('streak').textContent=s.current;$('best').textContent=s.best+' 天';$('total').textContent=Object.values(state.records).filter(r=>r.status==='success').length+' 天';$('todayLabel').textContent=today().slice(5).replace('-',' / ');const r=state.records[today()];$('checkBtn').textContent=r?'修改今天的记录':'记录今天';$('todayStatus').textContent=!r?'今天还未记录':r.status==='success'?'✓ 今天已成功':`今天未成功${eventLabel(r)?' · '+eventLabel(r):''}`;renderCalendar();renderDashboard();renderBackup();}
function eventLabel(r){const a=[];if(r.sex)a.push(`💞 做爱 ${r.sex} 次`);if(r.masturbation)a.push(`✋ 自慰 ${r.masturbation} 次`);if(r.legacyReset&&!r.sex&&!r.masturbation)a.push('旧版重置，方式未记录');return a.join(' · ');}
function renderCalendar(){const y=viewDate.getFullYear(),m=viewDate.getMonth();$('monthTitle').textContent=`${y} 年 ${m+1} 月`;$('calendar').replaceChildren();const first=new Date(y,m,1),count=new Date(y,m+1,0).getDate();for(let i=0;i<(first.getDay()+6)%7;i++){const blank=document.createElement('span');blank.setAttribute('aria-hidden','true');$('calendar').append(blank);}
 for(let d=1;d<=count;d++){const date=C.day(new Date(y,m,d)),r=state.records[date],button=document.createElement('button');button.type='button';button.className='calendar-day'+(r?' '+r.status:'')+(date===today()?' is-today':'')+(date>today()?' future':'');button.dataset.date=date;button.disabled=date>today();const number=document.createElement('span');number.textContent=d;const marker=document.createElement('small');marker.textContent=r?.status==='success'?'✓':r?.status==='failure'?(r.sex?'💞':'')+(r.masturbation?'✋':'')||'•':'';button.append(number,marker);button.setAttribute('aria-label',`${date} ${r?.status==='success'?'成功':r?'未成功':'未记录'}${r?' '+eventLabel(r):''}`);if(date===today())button.setAttribute('aria-current','date');button.onclick=()=>openRecord(date);$('calendar').append(button);}
 $('prevMonth').disabled=y<=1900&&m===0;$('nextMonth').disabled=C.day(new Date(y,m+1,1))>today();
}
function renderDashboard(){const start=rangeStart(),end=today(),actualStart=start<state.startDate?state.startDate:start,s=C.stats(state,start,end);$('rangeLabel').textContent=range==='all'?'全部记录':range==='month'?'本月':`近 ${range} 天`;$('rate').textContent=s.days?s.rate+'%':'—';$('coverage').textContent=s.coverage+'%';$('rateRing').style.setProperty('--progress',s.coverage+'%');$('rateDescription').textContent=`${actualStart} 至 ${end} · 成功 ${s.success} / ${s.days} 天（含未记录日期）`;for(const [id,n] of Object.entries({successDays:s.success,failureDays:s.failure,unknownDays:s.unknown,eventTotal:s.sex+s.masturbation}))$(id).textContent=n;$('sexTotal').textContent=s.sex+' 次';$('soloTotal').textContent=s.masturbation+' 次';const events=s.sex+s.masturbation;$('sexBar').style.width=(events?s.sex/events*100:0)+'%';$('soloBar').style.width=(events?s.masturbation/events*100:0)+'%';
 $('trend').replaceChildren();const now=C.parse(today());for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),a=C.day(d),b=C.day(new Date(d.getFullYear(),d.getMonth()+1,0)),month=C.stats(state,a,b>end?end:b),col=document.createElement('div');col.className='trend-col';const value=document.createElement('div');value.className='trend-value';value.textContent=month.days?month.rate+'%':'—';const track=document.createElement('div');track.className='trend-track';const bar=document.createElement('div');bar.className='trend-bar';bar.style.height=(month.days?month.rate:0)+'%';track.append(bar);const label=document.createElement('span');label.textContent=(d.getMonth()+1)+'月';col.append(value,track,label);col.setAttribute('aria-label',`${d.getFullYear()}年${d.getMonth()+1}月，${month.days?'成功 '+month.success+' / '+month.days+' 天':'尚未追踪'}`);$('trend').append(col);}
 $('history').replaceChildren();const records=Object.entries(state.records).filter(([d])=>d>=actualStart&&d<=end).sort(([a],[b])=>b.localeCompare(a));if(!records.length){const p=document.createElement('p');p.className='muted';p.textContent='这段时间还没有记录。去打卡页选择一天开始吧。';$('history').append(p);}
 for(const [d,r] of records){const button=document.createElement('button'),left=document.createElement('div'),date=document.createElement('div'),detail=document.createElement('small'),status=document.createElement('span');date.textContent=d;detail.textContent=[eventLabel(r),r.note].filter(Boolean).join(' · ');left.append(date);if(detail.textContent)left.append(detail);status.className='status-text '+r.status;status.textContent=r.status==='success'?'✓ 成功':'未成功';button.append(left,status);button.onclick=()=>openRecord(d);$('history').append(button);}
}
function renderBackup(){$('startInfo').textContent=`当前起始日：${state.startDate}`;const exported=localGet(BACKUP_TIME);$('backupInfo').textContent=exported?`上次导出：${new Date(exported).toLocaleString('zh-CN')}`:'还没有导出备份。';$('legacyHistory').replaceChildren();if(!state.resets.length){const p=document.createElement('p');p.className='muted footnote';p.textContent='暂无旧版重置记录。新记录请在月历中编辑。';$('legacyHistory').append(p);}for(const r of [...state.resets].sort((a,b)=>b.date.localeCompare(a.date))){const div=document.createElement('div');div.className='legacy-item';div.textContent=`${r.date} · ${r.note||'重置计时'}`;$('legacyHistory').append(div);}}
function selectedStatus(){return document.querySelector('input[name=status]:checked')?.value||'unknown';}
function syncStatus(){const fail=selectedStatus()==='failure';$('methodFields').hidden=!fail;$('sexCount').disabled=!fail;$('soloCount').disabled=!fail;$('recordNote').disabled=selectedStatus()==='unknown';$('recordHint').textContent=selectedStatus()==='unknown'?'保存“未记录”会清除这一天的每日记录，不影响其他日期。':'';}
function populateRecord(date){const r=state.records[date];document.querySelector(`input[name=status][value=${r?.status||'unknown'}]`).checked=true;$('sexCount').value=r?.sex||0;$('soloCount').value=r?.masturbation||0;$('recordNote').value=r?.note||'';syncStatus();}
function openRecord(date=today()){$('recordDate').max=today();$('recordDate').value=date;populateRecord(date);$('recordDialog').showModal();}
$('recordDate').onchange=()=>{const d=$('recordDate').value;if(C.valid(d)&&d<=today())populateRecord(d);};
for(const input of document.querySelectorAll('input[name=status]'))input.onchange=syncStatus;
$('recordForm').onsubmit=async e=>{e.preventDefault();const d=$('recordDate').value,status=selectedStatus();if(!C.valid(d)||d>today())return toast('请选择有效的今天或过去日期');const sex=status==='failure'?Number($('sexCount').value):0,masturbation=status==='failure'?Number($('soloCount').value):0;if([sex,masturbation].some(n=>!Number.isInteger(n)||n<0||n>99))return toast('次数应为 0–99 的整数');if(status==='unknown')delete state.records[d];else{const old=state.records[d];state.records[d]={status,sex,masturbation,note:$('recordNote').value.trim(),legacyReset:!!old?.legacyReset&&status==='failure'&&!sex&&!masturbation};if(d<state.startDate)state.startDate=d;}viewDate=C.parse(d);$('recordDialog').close();render();const ok=await persist();toast(ok?'记录已保存':'保存失败，请导出备份');if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});};
$('checkBtn').onclick=()=>openRecord();$('chooseDate').onclick=()=>openRecord();$('jumpToday').onclick=()=>{viewDate=C.parse(today());renderCalendar();};$('prevMonth').onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);renderCalendar();};$('nextMonth').onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);renderCalendar();};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{for(const x of document.querySelectorAll('[data-tab]')){const active=x===b;x.classList.toggle('active',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');$(x.dataset.tab+'Panel').hidden=!active;}render();window.scrollTo(0,0);};
for(const b of document.querySelectorAll('[data-range]'))b.onclick=()=>{range=b.dataset.range;for(const x of document.querySelectorAll('[data-range]')){x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));}renderDashboard();};
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('settingsBtn').onclick=()=>{$('goalName').value=state.goalName;$('motto').value=state.motto;$('settingsDialog').showModal();};$('settingsForm').onsubmit=async e=>{e.preventDefault();state.goalName=$('goalName').value.trim()||'禁欲打卡';state.motto=$('motto').value.trim();$('settingsDialog').close();render();await persist();};
$('editStartBtn').onclick=()=>{$('startDate').value=state.startDate;$('startDate').max=today();$('startDialog').showModal();};$('startForm').onsubmit=async e=>{e.preventDefault();const d=$('startDate').value,earliest=Object.keys(state.records).sort()[0];if(!C.valid(d)||d>today())return toast('请选择有效的今天或过去日期');if(earliest&&d>earliest)return toast('起始日不能晚于最早记录 '+earliest);state.startDate=d;$('startDialog').close();render();await persist();};
$('exportBtn').onclick=async()=>{await writeQueue;const payload={app:'禁欲打卡',exportedAt:new Date().toISOString(),state},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`禁欲打卡备份_${today()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);try{localStorage.setItem(BACKUP_TIME,JSON.stringify(Date.now()));}catch{}renderBackup();toast('备份已生成，请保存到“文件”或 iCloud Drive');};
$('importBtn').onclick=()=>$('fileInput').click();
$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw Error('文件过大，请选择打卡 JSON 备份');const raw=JSON.parse(await f.text()),imported=C.normalize(raw.state||raw);const n=Object.keys(imported.records).length;if(!confirm(`导入将替换当前记录（备份含 ${n} 个日期）。导入前会自动保留当前记录供撤销。继续吗？`))return;await writeQueue;const old=JSON.parse(JSON.stringify(state));let retained=false;try{localStorage.setItem(UNDO,JSON.stringify(old));retained=true;}catch{}try{await dbWrite(old,UNDO);retained=true;}catch{}if(!retained)throw Error('无法保留当前记录，请先手动导出备份后再试');state=imported;render();const ok=await persist();$('undoImport').hidden=false;toast(ok?'备份已恢复':'已导入，但保存失败，请导出备份');}catch(error){toast(error.message==='Unexpected end of JSON input'?'备份文件不完整':error instanceof SyntaxError?'请选择有效的 JSON 备份':error.message);}finally{e.target.value='';}};
$('undoImport').onclick=async()=>{let old=localGet(UNDO);try{const b=await dbRead(UNDO);if(b&&(!old||b.modifiedAt>old.modifiedAt))old=b;}catch{}if(!old)return toast('没有可撤销的导入');try{const restored=C.normalize(old);if(!confirm('恢复导入前的记录？当前记录将被替换。'))return;state=restored;render();await persist();toast('已恢复导入前的记录');}catch{toast('恢复数据无法读取');}};
$('refreshBtn').onclick=()=>location.reload();
if('serviceWorker' in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');reg.update().catch(()=>{});}catch{}});navigator.serviceWorker.addEventListener('controllerchange',()=>{$('updateBanner').hidden=false;});}
window.addEventListener('pageshow',()=>{if(!$('app').inert)render();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!$('app').inert)render();});
window.addEventListener('storage',e=>{if(e.key===KEY&&!document.querySelector('dialog[open]')){try{const s=C.normalize(JSON.parse(e.newValue));if(s.modifiedAt>state.modifiedAt){state=s;render();toast('已同步另一页面的记录');}}catch{}}});
load().catch(()=>{$('app').inert=false;$('storageStatus').textContent='读取记录遇到问题，请导入备份或立即导出当前记录。';$('storageStatus').classList.add('warning');});
